### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Nirmal-Kr** [codex-iter/text-editor#1]
The person using the code won't be having the icons we have stated here. Any help regarding that, can we make a zip file of all the icons and put it in our repo for the user to download

**Comment by SubhrajitPrusty** [comment]
See, we already told you that the project need not be a single file script.
So, you can add the files into a folder, upload it and modify your icon file paths accordingly. Or you can use system provided icons for different distributions.

**Comment by AshisPadhi** [comment]
fixed this issue #5
